name: GitHub Issues to TestLink

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
      issue_title:
        required: true
        type: string
      issue_body:
        required: true
        type: string
      issue_author:
        required: true
        type: string
      folder_id:
        required: true
        type: string

jobs:
  generate-xml:
    runs-on: [self-hosted, linux, taazaa.shared.runner.01]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install playwright @actions/core @actions/github

      - name: Create requirements directory
        run: mkdir -p requirements

      - name: Generate Requirement XML with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: node .github/scripts/generate-xml.js
        env:
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          ISSUE_TITLE: ${{ inputs.issue_title }}
          ISSUE_BODY: ${{ inputs.issue_body }}
          ISSUE_AUTHOR: ${{ inputs.issue_author }}
          REPO_URL: ${{ github.repositoryUrl }}

      - name: Upload Artifact (XML File)
        uses: actions/upload-artifact@v4
        with:
          name: requirement-xml
          path: requirements/requirement-${{ inputs.issue_number }}.xml

  upload-to-testlink:
    runs-on: [self-hosted, linux, taazaa.shared.runner.01]
    needs: generate-xml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: requirement-xml
          path: requirements/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install playwright

      - name: Run Playwright Script (Upload to TestLink) with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 60
          command: |
            echo "=== Debug Info ==="
            echo "XML files available:"
            ls -la requirements/
            echo "XML content:"
            cat requirements/requirement-*.xml
            
            echo "=== Running Upload Script ==="
            node .github/scripts/upload-to-testlink.js
        env:
          TESTLINK_URL: ${{ secrets.TESTLINK_URL }}
          TESTLINK_USER: ${{ secrets.TESTLINK_USER }}
          TESTLINK_PASS: ${{ secrets.TESTLINK_PASS }}
          FOLDER_ID: ${{ inputs.folder_id }}   # 👈 pass folder id here
